[package]
name = "mqtt-policy"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2018"

[dependencies]
lazy_static = "1.4"
tracing = "0.1"

mqtt-broker = { path = "../mqtt-broker" }
policy = { path = "../policy" }

